services:

  db:
    image: postgres:15-alpine
    container_name: reservation_db
    environment:
      POSTGRES_USER:     coworking_user
      POSTGRES_PASSWORD: coworking_pass
      POSTGRES_DB:       reservationsdb
    volumes:
      - reservation_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coworking_user -d reservationsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  reservation-service:
    build: .
    container_name: coworking_reservation
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      TZ: America/Caracas
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      db:
        condition: service_healthy

volumes:
  reservation_postgres_data:

networks:
    default:
      external: true
      name: coworking_net
