version: "3.9"

services:

  db:
    image: postgres:15-alpine
    container_name: space_db
    environment:
      POSTGRES_USER:     coworking_user
      POSTGRES_PASSWORD: coworking_pass
      POSTGRES_DB:       spacesdb
    volumes:
      - space_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coworking_user -d spacesdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  space-service:
    build: .
    container_name: coworking_space
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  space_postgres_data:
